apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-three
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: service-three
  template:
    metadata:
      labels:
        app: service-three
    spec:
      containers:
      - name: service-three
        image: israahassan1/service-three:latest 
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: SERVICE3_DB
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: SERVICE3_DB
---
apiVersion: v1
kind: Service
metadata:
  name: service-three
spec:
  selector:
    app: service-three
  ports:
  - protocol: TCP
    port: 80       
    targetPort: 80 
  type: ClusterIP   